version: "3.8"

services:
  plc-service:
    build: .
    container_name: plc-service
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - plc-db
    networks:
      - shared-kafka-net

  plc-db:
    image: postgres:15
    container_name: plc-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - plc_data:/var/lib/postgresql/data
    networks:
      - shared-kafka-net

volumes:
  plc_data:

networks:
  shared-kafka-net:
    external: true
