"""message field added default server

Revision ID: 8a1acf933c07
Revises: 
Create Date: 2025-07-25 13:09:46.813320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1acf933c07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plc_commands', sa.Column('message', sa.String(), server_default='{}', nullable=False))
    op.create_index(op.f('ix_plc_commands_message'), 'plc_commands', ['message'], unique=False)
    op.drop_column('plc_commands', 'bucket_id')
    op.drop_column('plc_commands', 'qty')
    op.drop_column('plc_commands', 'material_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plc_commands', sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plc_commands', sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plc_commands', sa.Column('bucket_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_plc_commands_message'), table_name='plc_commands')
    op.drop_column('plc_commands', 'message')
    # ### end Alembic commands ###
